// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqndutlzwxjnpmgrqwjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxbmR1dGx6d3hqbnBtZ3Jxd2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTU4OTYsImV4cCI6MjA2OTE5MTg5Nn0.yc_sfTRtGZJ6SX3FFNH5tIbRhNNGPeO_BeQkQRrm6nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});